#pragma once

#include "tests/test_cases/TestCasesArraysStrings.h"
#include "tests/test_cases/TestCasesBacktracking.h"
#include "tests/test_cases/TestCasesBinarySearch.h"
#include "tests/test_cases/TestCasesBitManipulation.h"
#include "tests/test_cases/TestCasesDesign.h"
#include "tests/test_cases/TestCasesDynamicProgramming.h"
#include "tests/test_cases/TestCasesGraphs.h"
#include "tests/test_cases/TestCasesHashmapsSets.h"
#include "tests/test_cases/TestCasesHeaps.h"
#include "tests/test_cases/TestCasesLinkedLists.h"
#include "tests/test_cases/TestCasesOther.h"
#include "tests/test_cases/TestCasesSlidingWindow.h"
#include "tests/test_cases/TestCasesStacks.h"
#include "tests/test_cases/TestCasesTrees.h"
#include "tests/test_cases/TestCasesTwoPointers.h"
